# 这个是必须的, 代表用于项目文档的主标题
site_name: 智海文档库

# 设置站点url, 这将添加带有规范的url的link标签到HTML头部, 默认为null
site_url: null

# 如果设置了该项, 每个页面将会添加一个链接到你的github或是bitbucket版本库
repo_name: null

# 站点描述
site_description: zhihaiTECH文档库

# 站点作者, 这将在HTML头部添加一个meta标签, 默认值null
site_author: zhihai

# 设置favicon, 需要将favicon.ico放到/docs目录
site_favicon: favicon.ico

# 设置站点版权信息
copyright: ©zhihaiTECH 2013-2017

# 设置google站点分析工具
google_analytics: ['UA-32763568', 'mkdocs.org']

# 设置需要生成的页面范围, 列表中每一行用一个字符串列表表示一个页面
# 第一个字符串代表源文件的路径, 应为相对于doc_dir的路径
# 其余字符串代表导航中的页面标题
# docs_dir默认值为docs
# 如果有大量文档, 需要用导航条来按目录来组织你的导航, 可以在pages选项中包含一个额外的字符串来表示导航头部
pages:
- [index.md, 主页]
- [help/guide.md, 帮助, '用户指南']
- [help/yaml.md, 帮助, '用户指南']
- [about.md, 关于]

# 设置站点主题, 默认值为mkdocs
theme: readthedocs

# 设置自定义主图
theme_dir: null

# 设置包含markdown源码的目录, 默认值是docs
docs_dir: docs

# 设置生成的HTML和其他文件所在的目录, 默认值是site
site_dir: site

# 设定主题所需要的额外的样式文件
# extra_css: 默认值将包含docs_dir目录下的样式文件, 如果没有找到则为[]

# 设置主题所需要的额外的脚本文件
# extra_javascript: 默认情况下extra_javascript将包含doc_dir目录下的脚本文件, 如果没有找到则为[]

# 预览控制, true表现性对用户更好
# use_directory_urls: true

# 设置运行链接地址, 默认为127.0.0.1:8000
dev_addr: 0.0.0.0:8000